DROP DATABASE ManagerPass;
CREATE DATABASE IF NOT EXISTS ManagerPass;
USE ManagerPass;
CREATE TABLE IF NOT EXISTS DatosUsers (
id INT(11) NOT NULL AUTO_INCREMENT,
username VARCHAR(25) NOT NULL,
ape1 VARCHAR(25) NOT NULL,
ape2 VARCHAR(25) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(300) NOT NULL,
FechaCreacionUser TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS links (
id INT(11) NOT NULL AUTO_INCREMENT,
title VARCHAR(150) NOT NULL, 
url VARCHAR(255) NOT NULL,
email VARCHAR(400) NOT NULL,
password VARCHAR(400) NOT NULL,
user_id INT(11) NOT NULL,
FechaCreacionLinks  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id),
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES DatosUsers(id)
);

SELECT * FROM DatosUsers;
SELECT * FROM links;